Parameters:
  KeyPairName:
    Type: String

Resources:
  DatabaseSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from everywhere
      SecurityGroupIngress:
        IpProtocol: -1
        CidrIp: 0.0.0.0/0
  MongoA1:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          
          cat > /etc/yum.repos.d/mongodb-org-4.4.repo <<EOF
          [mongodb-org-4.4]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/4.4/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
          EOF
          
          yum install mongodb-org -y

          sed -i '29s/.*/  bindIp: 0.0.0.0/' /etc/mongod.conf
          sed -i '36s/.*/replication:/' /etc/mongod.conf
          sed -i '37s/.*/  replSetName: hello/' /etc/mongod.conf

          systemctl start mongod
   
      ImageId: ami-0f86a70488991335e
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref DatabaseSG
      KeyName: !Ref KeyPairName
      AvailabilityZone: ap-southeast-1a
      Tags:
        - Key: "Name"
          Value: mongoA1
 
  MongoA2:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          
          cat > /etc/yum.repos.d/mongodb-org-4.4.repo <<EOF
          [mongodb-org-4.4]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/4.4/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
          EOF
          
          yum install mongodb-org -y

          sed -i '29s/.*/  bindIp: 0.0.0.0/' /etc/mongod.conf
          sed -i '36s/.*/replication:/' /etc/mongod.conf
          sed -i '37s/.*/  replSetName: hello/' /etc/mongod.conf

          systemctl start mongod

      ImageId: ami-0f86a70488991335e
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref DatabaseSG
      KeyName: !Ref KeyPairName
      AvailabilityZone: ap-southeast-1a
      Tags:
        - Key: "Name"
          Value: mongoA2

  MongoA3:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          
          cat > /etc/yum.repos.d/mongodb-org-4.4.repo <<EOF
          [mongodb-org-4.4]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/4.4/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
          EOF
          
          yum install mongodb-org -y

          sed -i '29s/.*/  bindIp: 0.0.0.0/' /etc/mongod.conf
          sed -i '36s/.*/replication:/' /etc/mongod.conf
          sed -i '37s/.*/  replSetName: hello/' /etc/mongod.conf

          systemctl start mongod

      ImageId: ami-0f86a70488991335e
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref DatabaseSG
      KeyName: !Ref KeyPairName
      AvailabilityZone: ap-southeast-1a
      Tags:
        - Key: "Name"
          Value: mongoA3

  MongoB1:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          
          cat > /etc/yum.repos.d/mongodb-org-4.4.repo <<EOF
          [mongodb-org-4.4]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/4.4/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
          EOF
          
          yum install mongodb-org -y

          sed -i '29s/.*/  bindIp: 0.0.0.0/' /etc/mongod.conf
          sed -i '36s/.*/replication:/' /etc/mongod.conf
          sed -i '37s/.*/  replSetName: hello/' /etc/mongod.conf

          systemctl start mongod

      ImageId: ami-0f86a70488991335e
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref DatabaseSG
      KeyName: !Ref KeyPairName
      AvailabilityZone: ap-southeast-1b
      Tags:
        - Key: "Name"
          Value: mongoB1

  MongoB2:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          
          cat > /etc/yum.repos.d/mongodb-org-4.4.repo <<EOF
          [mongodb-org-4.4]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/4.4/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
          EOF
          
          yum install mongodb-org -y

          sed -i '29s/.*/  bindIp: 0.0.0.0/' /etc/mongod.conf
          sed -i '36s/.*/replication:/' /etc/mongod.conf
          sed -i '37s/.*/  replSetName: hello/' /etc/mongod.conf

          systemctl start mongod

      ImageId: ami-0f86a70488991335e
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref DatabaseSG
      KeyName: !Ref KeyPairName
      AvailabilityZone: ap-southeast-1b
      Tags:
        - Key: "Name"
          Value: mongoB2

  Arbiter:
    Type: AWS::EC2::Instance
    DependsOn: 
      - MongoA1
      - MongoA2
      - MongoA3
      - MongoB1
      - MongoB2
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          
          cat > /etc/yum.repos.d/mongodb-org-4.4.repo <<EOF
          [mongodb-org-4.4]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/4.4/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
          EOF
          
          yum install mongodb-org -y

          mkdir /var/lib/mongo/arb
          chown -R mongod:mongod /var/lib/mongo/arb/
          chmod 777 /var/lib/mongo/arb

          cat > /home/ec2-user/copy-paste <<EOF
          # STEP 1
          # Run this command from mongo shell of first ReplicaSet member:
          rs.initiate( {
          _id : "hello",
          members: [
              { _id: 0, host: "${MongoA1.PublicIp}:27017", priority: 9 },
              { _id: 1, host: "${MongoA2.PublicIp}:27017", priority: 8 },
              { _id: 2, host: "${MongoA3.PublicIp}:27017", priority: 6 },
              { _id: 3, host: "${MongoB1.PublicIp}:27017" },
              { _id: 4, host: "${MongoB2.PublicIp}:27017" }]})
          
          # STEP 2
          # Run this command from Arbiter:
          mongod --port 27017 --dbpath /var/lib/mongo/arb --replSet hello --bind_ip 0.0.0.0
          
          # STEP 3
          # Run this command from mongo shell of first ReplicaSet member:
          rs.addArb("$(curl http://169.254.169.254/latest/meta-data/public-ipv4 -s):27017")
          EOF

      ImageId: ami-0f86a70488991335e
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref DatabaseSG
      KeyName: !Ref KeyPairName
      AvailabilityZone: ap-southeast-1b
      Tags:
        - Key: "Name"
          Value: mongoB3_arbiter


